# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/vinnie/Desktop/Rasberry Pi/Insteon/PLM code/InsteonServer"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/vinnie/Desktop/Rasberry Pi/Insteon/PLM code/InsteonServer"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/vinnie/Desktop/Rasberry Pi/Insteon/PLM code/InsteonServer/CMakeFiles" "/Users/vinnie/Desktop/Rasberry Pi/Insteon/PLM code/InsteonServer//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/vinnie/Desktop/Rasberry Pi/Insteon/PLM code/InsteonServer/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named copy_assets

# Build rule for target.
copy_assets: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 copy_assets
.PHONY : copy_assets

# fast build rule for target.
copy_assets/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/copy_assets.dir/build.make CMakeFiles/copy_assets.dir/build
.PHONY : copy_assets/fast

#=============================================================================
# Target rules for targets named InsteonMgr

# Build rule for target.
InsteonMgr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 InsteonMgr
.PHONY : InsteonMgr

# fast build rule for target.
InsteonMgr/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/build
.PHONY : InsteonMgr/fast

InsteonMgr/Action.o: InsteonMgr/Action.cpp.o
.PHONY : InsteonMgr/Action.o

# target to build an object file
InsteonMgr/Action.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/Action.cpp.o
.PHONY : InsteonMgr/Action.cpp.o

InsteonMgr/Action.i: InsteonMgr/Action.cpp.i
.PHONY : InsteonMgr/Action.i

# target to preprocess a source file
InsteonMgr/Action.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/Action.cpp.i
.PHONY : InsteonMgr/Action.cpp.i

InsteonMgr/Action.s: InsteonMgr/Action.cpp.s
.PHONY : InsteonMgr/Action.s

# target to generate assembly for a file
InsteonMgr/Action.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/Action.cpp.s
.PHONY : InsteonMgr/Action.cpp.s

InsteonMgr/DeviceID.o: InsteonMgr/DeviceID.cpp.o
.PHONY : InsteonMgr/DeviceID.o

# target to build an object file
InsteonMgr/DeviceID.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/DeviceID.cpp.o
.PHONY : InsteonMgr/DeviceID.cpp.o

InsteonMgr/DeviceID.i: InsteonMgr/DeviceID.cpp.i
.PHONY : InsteonMgr/DeviceID.i

# target to preprocess a source file
InsteonMgr/DeviceID.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/DeviceID.cpp.i
.PHONY : InsteonMgr/DeviceID.cpp.i

InsteonMgr/DeviceID.s: InsteonMgr/DeviceID.cpp.s
.PHONY : InsteonMgr/DeviceID.s

# target to generate assembly for a file
InsteonMgr/DeviceID.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/DeviceID.cpp.s
.PHONY : InsteonMgr/DeviceID.cpp.s

InsteonMgr/DeviceInfo.o: InsteonMgr/DeviceInfo.cpp.o
.PHONY : InsteonMgr/DeviceInfo.o

# target to build an object file
InsteonMgr/DeviceInfo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/DeviceInfo.cpp.o
.PHONY : InsteonMgr/DeviceInfo.cpp.o

InsteonMgr/DeviceInfo.i: InsteonMgr/DeviceInfo.cpp.i
.PHONY : InsteonMgr/DeviceInfo.i

# target to preprocess a source file
InsteonMgr/DeviceInfo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/DeviceInfo.cpp.i
.PHONY : InsteonMgr/DeviceInfo.cpp.i

InsteonMgr/DeviceInfo.s: InsteonMgr/DeviceInfo.cpp.s
.PHONY : InsteonMgr/DeviceInfo.s

# target to generate assembly for a file
InsteonMgr/DeviceInfo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/DeviceInfo.cpp.s
.PHONY : InsteonMgr/DeviceInfo.cpp.s

InsteonMgr/Event.o: InsteonMgr/Event.cpp.o
.PHONY : InsteonMgr/Event.o

# target to build an object file
InsteonMgr/Event.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/Event.cpp.o
.PHONY : InsteonMgr/Event.cpp.o

InsteonMgr/Event.i: InsteonMgr/Event.cpp.i
.PHONY : InsteonMgr/Event.i

# target to preprocess a source file
InsteonMgr/Event.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/Event.cpp.i
.PHONY : InsteonMgr/Event.cpp.i

InsteonMgr/Event.s: InsteonMgr/Event.cpp.s
.PHONY : InsteonMgr/Event.s

# target to generate assembly for a file
InsteonMgr/Event.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/Event.cpp.s
.PHONY : InsteonMgr/Event.cpp.s

InsteonMgr/InsteonALDB.o: InsteonMgr/InsteonALDB.cpp.o
.PHONY : InsteonMgr/InsteonALDB.o

# target to build an object file
InsteonMgr/InsteonALDB.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/InsteonALDB.cpp.o
.PHONY : InsteonMgr/InsteonALDB.cpp.o

InsteonMgr/InsteonALDB.i: InsteonMgr/InsteonALDB.cpp.i
.PHONY : InsteonMgr/InsteonALDB.i

# target to preprocess a source file
InsteonMgr/InsteonALDB.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/InsteonALDB.cpp.i
.PHONY : InsteonMgr/InsteonALDB.cpp.i

InsteonMgr/InsteonALDB.s: InsteonMgr/InsteonALDB.cpp.s
.PHONY : InsteonMgr/InsteonALDB.s

# target to generate assembly for a file
InsteonMgr/InsteonALDB.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/InsteonALDB.cpp.s
.PHONY : InsteonMgr/InsteonALDB.cpp.s

InsteonMgr/InsteonAPISecretMgr.o: InsteonMgr/InsteonAPISecretMgr.cpp.o
.PHONY : InsteonMgr/InsteonAPISecretMgr.o

# target to build an object file
InsteonMgr/InsteonAPISecretMgr.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/InsteonAPISecretMgr.cpp.o
.PHONY : InsteonMgr/InsteonAPISecretMgr.cpp.o

InsteonMgr/InsteonAPISecretMgr.i: InsteonMgr/InsteonAPISecretMgr.cpp.i
.PHONY : InsteonMgr/InsteonAPISecretMgr.i

# target to preprocess a source file
InsteonMgr/InsteonAPISecretMgr.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/InsteonAPISecretMgr.cpp.i
.PHONY : InsteonMgr/InsteonAPISecretMgr.cpp.i

InsteonMgr/InsteonAPISecretMgr.s: InsteonMgr/InsteonAPISecretMgr.cpp.s
.PHONY : InsteonMgr/InsteonAPISecretMgr.s

# target to generate assembly for a file
InsteonMgr/InsteonAPISecretMgr.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/InsteonAPISecretMgr.cpp.s
.PHONY : InsteonMgr/InsteonAPISecretMgr.cpp.s

InsteonMgr/InsteonCmdQueue.o: InsteonMgr/InsteonCmdQueue.cpp.o
.PHONY : InsteonMgr/InsteonCmdQueue.o

# target to build an object file
InsteonMgr/InsteonCmdQueue.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/InsteonCmdQueue.cpp.o
.PHONY : InsteonMgr/InsteonCmdQueue.cpp.o

InsteonMgr/InsteonCmdQueue.i: InsteonMgr/InsteonCmdQueue.cpp.i
.PHONY : InsteonMgr/InsteonCmdQueue.i

# target to preprocess a source file
InsteonMgr/InsteonCmdQueue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/InsteonCmdQueue.cpp.i
.PHONY : InsteonMgr/InsteonCmdQueue.cpp.i

InsteonMgr/InsteonCmdQueue.s: InsteonMgr/InsteonCmdQueue.cpp.s
.PHONY : InsteonMgr/InsteonCmdQueue.s

# target to generate assembly for a file
InsteonMgr/InsteonCmdQueue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/InsteonCmdQueue.cpp.s
.PHONY : InsteonMgr/InsteonCmdQueue.cpp.s

InsteonMgr/InsteonDB.o: InsteonMgr/InsteonDB.cpp.o
.PHONY : InsteonMgr/InsteonDB.o

# target to build an object file
InsteonMgr/InsteonDB.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/InsteonDB.cpp.o
.PHONY : InsteonMgr/InsteonDB.cpp.o

InsteonMgr/InsteonDB.i: InsteonMgr/InsteonDB.cpp.i
.PHONY : InsteonMgr/InsteonDB.i

# target to preprocess a source file
InsteonMgr/InsteonDB.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/InsteonDB.cpp.i
.PHONY : InsteonMgr/InsteonDB.cpp.i

InsteonMgr/InsteonDB.s: InsteonMgr/InsteonDB.cpp.s
.PHONY : InsteonMgr/InsteonDB.s

# target to generate assembly for a file
InsteonMgr/InsteonDB.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/InsteonDB.cpp.s
.PHONY : InsteonMgr/InsteonDB.cpp.s

InsteonMgr/InsteonDevice.o: InsteonMgr/InsteonDevice.cpp.o
.PHONY : InsteonMgr/InsteonDevice.o

# target to build an object file
InsteonMgr/InsteonDevice.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/InsteonDevice.cpp.o
.PHONY : InsteonMgr/InsteonDevice.cpp.o

InsteonMgr/InsteonDevice.i: InsteonMgr/InsteonDevice.cpp.i
.PHONY : InsteonMgr/InsteonDevice.i

# target to preprocess a source file
InsteonMgr/InsteonDevice.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/InsteonDevice.cpp.i
.PHONY : InsteonMgr/InsteonDevice.cpp.i

InsteonMgr/InsteonDevice.s: InsteonMgr/InsteonDevice.cpp.s
.PHONY : InsteonMgr/InsteonDevice.s

# target to generate assembly for a file
InsteonMgr/InsteonDevice.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/InsteonDevice.cpp.s
.PHONY : InsteonMgr/InsteonDevice.cpp.s

InsteonMgr/InsteonDeviceEventMgr.o: InsteonMgr/InsteonDeviceEventMgr.cpp.o
.PHONY : InsteonMgr/InsteonDeviceEventMgr.o

# target to build an object file
InsteonMgr/InsteonDeviceEventMgr.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/InsteonDeviceEventMgr.cpp.o
.PHONY : InsteonMgr/InsteonDeviceEventMgr.cpp.o

InsteonMgr/InsteonDeviceEventMgr.i: InsteonMgr/InsteonDeviceEventMgr.cpp.i
.PHONY : InsteonMgr/InsteonDeviceEventMgr.i

# target to preprocess a source file
InsteonMgr/InsteonDeviceEventMgr.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/InsteonDeviceEventMgr.cpp.i
.PHONY : InsteonMgr/InsteonDeviceEventMgr.cpp.i

InsteonMgr/InsteonDeviceEventMgr.s: InsteonMgr/InsteonDeviceEventMgr.cpp.s
.PHONY : InsteonMgr/InsteonDeviceEventMgr.s

# target to generate assembly for a file
InsteonMgr/InsteonDeviceEventMgr.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/InsteonDeviceEventMgr.cpp.s
.PHONY : InsteonMgr/InsteonDeviceEventMgr.cpp.s

InsteonMgr/InsteonLinking.o: InsteonMgr/InsteonLinking.cpp.o
.PHONY : InsteonMgr/InsteonLinking.o

# target to build an object file
InsteonMgr/InsteonLinking.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/InsteonLinking.cpp.o
.PHONY : InsteonMgr/InsteonLinking.cpp.o

InsteonMgr/InsteonLinking.i: InsteonMgr/InsteonLinking.cpp.i
.PHONY : InsteonMgr/InsteonLinking.i

# target to preprocess a source file
InsteonMgr/InsteonLinking.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/InsteonLinking.cpp.i
.PHONY : InsteonMgr/InsteonLinking.cpp.i

InsteonMgr/InsteonLinking.s: InsteonMgr/InsteonLinking.cpp.s
.PHONY : InsteonMgr/InsteonLinking.s

# target to generate assembly for a file
InsteonMgr/InsteonLinking.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/InsteonLinking.cpp.s
.PHONY : InsteonMgr/InsteonLinking.cpp.s

InsteonMgr/InsteonMgr.o: InsteonMgr/InsteonMgr.cpp.o
.PHONY : InsteonMgr/InsteonMgr.o

# target to build an object file
InsteonMgr/InsteonMgr.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/InsteonMgr.cpp.o
.PHONY : InsteonMgr/InsteonMgr.cpp.o

InsteonMgr/InsteonMgr.i: InsteonMgr/InsteonMgr.cpp.i
.PHONY : InsteonMgr/InsteonMgr.i

# target to preprocess a source file
InsteonMgr/InsteonMgr.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/InsteonMgr.cpp.i
.PHONY : InsteonMgr/InsteonMgr.cpp.i

InsteonMgr/InsteonMgr.s: InsteonMgr/InsteonMgr.cpp.s
.PHONY : InsteonMgr/InsteonMgr.s

# target to generate assembly for a file
InsteonMgr/InsteonMgr.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/InsteonMgr.cpp.s
.PHONY : InsteonMgr/InsteonMgr.cpp.s

InsteonMgr/InsteonPLM.o: InsteonMgr/InsteonPLM.cpp.o
.PHONY : InsteonMgr/InsteonPLM.o

# target to build an object file
InsteonMgr/InsteonPLM.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/InsteonPLM.cpp.o
.PHONY : InsteonMgr/InsteonPLM.cpp.o

InsteonMgr/InsteonPLM.i: InsteonMgr/InsteonPLM.cpp.i
.PHONY : InsteonMgr/InsteonPLM.i

# target to preprocess a source file
InsteonMgr/InsteonPLM.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/InsteonPLM.cpp.i
.PHONY : InsteonMgr/InsteonPLM.cpp.i

InsteonMgr/InsteonPLM.s: InsteonMgr/InsteonPLM.cpp.s
.PHONY : InsteonMgr/InsteonPLM.s

# target to generate assembly for a file
InsteonMgr/InsteonPLM.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/InsteonPLM.cpp.s
.PHONY : InsteonMgr/InsteonPLM.cpp.s

InsteonMgr/InsteonParser.o: InsteonMgr/InsteonParser.cpp.o
.PHONY : InsteonMgr/InsteonParser.o

# target to build an object file
InsteonMgr/InsteonParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/InsteonParser.cpp.o
.PHONY : InsteonMgr/InsteonParser.cpp.o

InsteonMgr/InsteonParser.i: InsteonMgr/InsteonParser.cpp.i
.PHONY : InsteonMgr/InsteonParser.i

# target to preprocess a source file
InsteonMgr/InsteonParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/InsteonParser.cpp.i
.PHONY : InsteonMgr/InsteonParser.cpp.i

InsteonMgr/InsteonParser.s: InsteonMgr/InsteonParser.cpp.s
.PHONY : InsteonMgr/InsteonParser.s

# target to generate assembly for a file
InsteonMgr/InsteonParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/InsteonParser.cpp.s
.PHONY : InsteonMgr/InsteonParser.cpp.s

InsteonMgr/InsteonValidator.o: InsteonMgr/InsteonValidator.cpp.o
.PHONY : InsteonMgr/InsteonValidator.o

# target to build an object file
InsteonMgr/InsteonValidator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/InsteonValidator.cpp.o
.PHONY : InsteonMgr/InsteonValidator.cpp.o

InsteonMgr/InsteonValidator.i: InsteonMgr/InsteonValidator.cpp.i
.PHONY : InsteonMgr/InsteonValidator.i

# target to preprocess a source file
InsteonMgr/InsteonValidator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/InsteonValidator.cpp.i
.PHONY : InsteonMgr/InsteonValidator.cpp.i

InsteonMgr/InsteonValidator.s: InsteonMgr/InsteonValidator.cpp.s
.PHONY : InsteonMgr/InsteonValidator.s

# target to generate assembly for a file
InsteonMgr/InsteonValidator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/InsteonValidator.cpp.s
.PHONY : InsteonMgr/InsteonValidator.cpp.s

InsteonMgr/LogMgr.o: InsteonMgr/LogMgr.cpp.o
.PHONY : InsteonMgr/LogMgr.o

# target to build an object file
InsteonMgr/LogMgr.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/LogMgr.cpp.o
.PHONY : InsteonMgr/LogMgr.cpp.o

InsteonMgr/LogMgr.i: InsteonMgr/LogMgr.cpp.i
.PHONY : InsteonMgr/LogMgr.i

# target to preprocess a source file
InsteonMgr/LogMgr.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/LogMgr.cpp.i
.PHONY : InsteonMgr/LogMgr.cpp.i

InsteonMgr/LogMgr.s: InsteonMgr/LogMgr.cpp.s
.PHONY : InsteonMgr/LogMgr.s

# target to generate assembly for a file
InsteonMgr/LogMgr.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/LogMgr.cpp.s
.PHONY : InsteonMgr/LogMgr.cpp.s

InsteonMgr/NotificationCenter.o: InsteonMgr/NotificationCenter.cpp.o
.PHONY : InsteonMgr/NotificationCenter.o

# target to build an object file
InsteonMgr/NotificationCenter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/NotificationCenter.cpp.o
.PHONY : InsteonMgr/NotificationCenter.cpp.o

InsteonMgr/NotificationCenter.i: InsteonMgr/NotificationCenter.cpp.i
.PHONY : InsteonMgr/NotificationCenter.i

# target to preprocess a source file
InsteonMgr/NotificationCenter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/NotificationCenter.cpp.i
.PHONY : InsteonMgr/NotificationCenter.cpp.i

InsteonMgr/NotificationCenter.s: InsteonMgr/NotificationCenter.cpp.s
.PHONY : InsteonMgr/NotificationCenter.s

# target to generate assembly for a file
InsteonMgr/NotificationCenter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/NotificationCenter.cpp.s
.PHONY : InsteonMgr/NotificationCenter.cpp.s

InsteonMgr/PLMStream.o: InsteonMgr/PLMStream.cpp.o
.PHONY : InsteonMgr/PLMStream.o

# target to build an object file
InsteonMgr/PLMStream.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/PLMStream.cpp.o
.PHONY : InsteonMgr/PLMStream.cpp.o

InsteonMgr/PLMStream.i: InsteonMgr/PLMStream.cpp.i
.PHONY : InsteonMgr/PLMStream.i

# target to preprocess a source file
InsteonMgr/PLMStream.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/PLMStream.cpp.i
.PHONY : InsteonMgr/PLMStream.cpp.i

InsteonMgr/PLMStream.s: InsteonMgr/PLMStream.cpp.s
.PHONY : InsteonMgr/PLMStream.s

# target to generate assembly for a file
InsteonMgr/PLMStream.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/PLMStream.cpp.s
.PHONY : InsteonMgr/PLMStream.cpp.s

InsteonMgr/ScheduleMgr.o: InsteonMgr/ScheduleMgr.cpp.o
.PHONY : InsteonMgr/ScheduleMgr.o

# target to build an object file
InsteonMgr/ScheduleMgr.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/ScheduleMgr.cpp.o
.PHONY : InsteonMgr/ScheduleMgr.cpp.o

InsteonMgr/ScheduleMgr.i: InsteonMgr/ScheduleMgr.cpp.i
.PHONY : InsteonMgr/ScheduleMgr.i

# target to preprocess a source file
InsteonMgr/ScheduleMgr.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/ScheduleMgr.cpp.i
.PHONY : InsteonMgr/ScheduleMgr.cpp.i

InsteonMgr/ScheduleMgr.s: InsteonMgr/ScheduleMgr.cpp.s
.PHONY : InsteonMgr/ScheduleMgr.s

# target to generate assembly for a file
InsteonMgr/ScheduleMgr.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/ScheduleMgr.cpp.s
.PHONY : InsteonMgr/ScheduleMgr.cpp.s

InsteonMgr/TimeStamp.o: InsteonMgr/TimeStamp.cpp.o
.PHONY : InsteonMgr/TimeStamp.o

# target to build an object file
InsteonMgr/TimeStamp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/TimeStamp.cpp.o
.PHONY : InsteonMgr/TimeStamp.cpp.o

InsteonMgr/TimeStamp.i: InsteonMgr/TimeStamp.cpp.i
.PHONY : InsteonMgr/TimeStamp.i

# target to preprocess a source file
InsteonMgr/TimeStamp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/TimeStamp.cpp.i
.PHONY : InsteonMgr/TimeStamp.cpp.i

InsteonMgr/TimeStamp.s: InsteonMgr/TimeStamp.cpp.s
.PHONY : InsteonMgr/TimeStamp.s

# target to generate assembly for a file
InsteonMgr/TimeStamp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/TimeStamp.cpp.s
.PHONY : InsteonMgr/TimeStamp.cpp.s

InsteonMgr/sleep.o: InsteonMgr/sleep.c.o
.PHONY : InsteonMgr/sleep.o

# target to build an object file
InsteonMgr/sleep.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/sleep.c.o
.PHONY : InsteonMgr/sleep.c.o

InsteonMgr/sleep.i: InsteonMgr/sleep.c.i
.PHONY : InsteonMgr/sleep.i

# target to preprocess a source file
InsteonMgr/sleep.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/sleep.c.i
.PHONY : InsteonMgr/sleep.c.i

InsteonMgr/sleep.s: InsteonMgr/sleep.c.s
.PHONY : InsteonMgr/sleep.s

# target to generate assembly for a file
InsteonMgr/sleep.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/sleep.c.s
.PHONY : InsteonMgr/sleep.c.s

InsteonMgr/sunset.o: InsteonMgr/sunset.cpp.o
.PHONY : InsteonMgr/sunset.o

# target to build an object file
InsteonMgr/sunset.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/sunset.cpp.o
.PHONY : InsteonMgr/sunset.cpp.o

InsteonMgr/sunset.i: InsteonMgr/sunset.cpp.i
.PHONY : InsteonMgr/sunset.i

# target to preprocess a source file
InsteonMgr/sunset.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/sunset.cpp.i
.PHONY : InsteonMgr/sunset.cpp.i

InsteonMgr/sunset.s: InsteonMgr/sunset.cpp.s
.PHONY : InsteonMgr/sunset.s

# target to generate assembly for a file
InsteonMgr/sunset.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/sunset.cpp.s
.PHONY : InsteonMgr/sunset.cpp.s

InsteonMgr/xxhash.o: InsteonMgr/xxhash.c.o
.PHONY : InsteonMgr/xxhash.o

# target to build an object file
InsteonMgr/xxhash.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/xxhash.c.o
.PHONY : InsteonMgr/xxhash.c.o

InsteonMgr/xxhash.i: InsteonMgr/xxhash.c.i
.PHONY : InsteonMgr/xxhash.i

# target to preprocess a source file
InsteonMgr/xxhash.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/xxhash.c.i
.PHONY : InsteonMgr/xxhash.c.i

InsteonMgr/xxhash.s: InsteonMgr/xxhash.c.s
.PHONY : InsteonMgr/xxhash.s

# target to generate assembly for a file
InsteonMgr/xxhash.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/InsteonMgr/xxhash.c.s
.PHONY : InsteonMgr/xxhash.c.s

Submodule/FooServer/src/REST/RESTServerConnection.o: Submodule/FooServer/src/REST/RESTServerConnection.cpp.o
.PHONY : Submodule/FooServer/src/REST/RESTServerConnection.o

# target to build an object file
Submodule/FooServer/src/REST/RESTServerConnection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/Submodule/FooServer/src/REST/RESTServerConnection.cpp.o
.PHONY : Submodule/FooServer/src/REST/RESTServerConnection.cpp.o

Submodule/FooServer/src/REST/RESTServerConnection.i: Submodule/FooServer/src/REST/RESTServerConnection.cpp.i
.PHONY : Submodule/FooServer/src/REST/RESTServerConnection.i

# target to preprocess a source file
Submodule/FooServer/src/REST/RESTServerConnection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/Submodule/FooServer/src/REST/RESTServerConnection.cpp.i
.PHONY : Submodule/FooServer/src/REST/RESTServerConnection.cpp.i

Submodule/FooServer/src/REST/RESTServerConnection.s: Submodule/FooServer/src/REST/RESTServerConnection.cpp.s
.PHONY : Submodule/FooServer/src/REST/RESTServerConnection.s

# target to generate assembly for a file
Submodule/FooServer/src/REST/RESTServerConnection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/Submodule/FooServer/src/REST/RESTServerConnection.cpp.s
.PHONY : Submodule/FooServer/src/REST/RESTServerConnection.cpp.s

Submodule/FooServer/src/REST/REST_URL.o: Submodule/FooServer/src/REST/REST_URL.cpp.o
.PHONY : Submodule/FooServer/src/REST/REST_URL.o

# target to build an object file
Submodule/FooServer/src/REST/REST_URL.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/Submodule/FooServer/src/REST/REST_URL.cpp.o
.PHONY : Submodule/FooServer/src/REST/REST_URL.cpp.o

Submodule/FooServer/src/REST/REST_URL.i: Submodule/FooServer/src/REST/REST_URL.cpp.i
.PHONY : Submodule/FooServer/src/REST/REST_URL.i

# target to preprocess a source file
Submodule/FooServer/src/REST/REST_URL.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/Submodule/FooServer/src/REST/REST_URL.cpp.i
.PHONY : Submodule/FooServer/src/REST/REST_URL.cpp.i

Submodule/FooServer/src/REST/REST_URL.s: Submodule/FooServer/src/REST/REST_URL.cpp.s
.PHONY : Submodule/FooServer/src/REST/REST_URL.s

# target to generate assembly for a file
Submodule/FooServer/src/REST/REST_URL.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/Submodule/FooServer/src/REST/REST_URL.cpp.s
.PHONY : Submodule/FooServer/src/REST/REST_URL.cpp.s

Submodule/FooServer/src/REST/http_parser.o: Submodule/FooServer/src/REST/http_parser.c.o
.PHONY : Submodule/FooServer/src/REST/http_parser.o

# target to build an object file
Submodule/FooServer/src/REST/http_parser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/Submodule/FooServer/src/REST/http_parser.c.o
.PHONY : Submodule/FooServer/src/REST/http_parser.c.o

Submodule/FooServer/src/REST/http_parser.i: Submodule/FooServer/src/REST/http_parser.c.i
.PHONY : Submodule/FooServer/src/REST/http_parser.i

# target to preprocess a source file
Submodule/FooServer/src/REST/http_parser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/Submodule/FooServer/src/REST/http_parser.c.i
.PHONY : Submodule/FooServer/src/REST/http_parser.c.i

Submodule/FooServer/src/REST/http_parser.s: Submodule/FooServer/src/REST/http_parser.c.s
.PHONY : Submodule/FooServer/src/REST/http_parser.s

# target to generate assembly for a file
Submodule/FooServer/src/REST/http_parser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/Submodule/FooServer/src/REST/http_parser.c.s
.PHONY : Submodule/FooServer/src/REST/http_parser.c.s

Submodule/FooServer/src/REST/yuarel.o: Submodule/FooServer/src/REST/yuarel.c.o
.PHONY : Submodule/FooServer/src/REST/yuarel.o

# target to build an object file
Submodule/FooServer/src/REST/yuarel.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/Submodule/FooServer/src/REST/yuarel.c.o
.PHONY : Submodule/FooServer/src/REST/yuarel.c.o

Submodule/FooServer/src/REST/yuarel.i: Submodule/FooServer/src/REST/yuarel.c.i
.PHONY : Submodule/FooServer/src/REST/yuarel.i

# target to preprocess a source file
Submodule/FooServer/src/REST/yuarel.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/Submodule/FooServer/src/REST/yuarel.c.i
.PHONY : Submodule/FooServer/src/REST/yuarel.c.i

Submodule/FooServer/src/REST/yuarel.s: Submodule/FooServer/src/REST/yuarel.c.s
.PHONY : Submodule/FooServer/src/REST/yuarel.s

# target to generate assembly for a file
Submodule/FooServer/src/REST/yuarel.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/Submodule/FooServer/src/REST/yuarel.c.s
.PHONY : Submodule/FooServer/src/REST/yuarel.c.s

Submodule/FooServer/src/RESTutils.o: Submodule/FooServer/src/RESTutils.cpp.o
.PHONY : Submodule/FooServer/src/RESTutils.o

# target to build an object file
Submodule/FooServer/src/RESTutils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/Submodule/FooServer/src/RESTutils.cpp.o
.PHONY : Submodule/FooServer/src/RESTutils.cpp.o

Submodule/FooServer/src/RESTutils.i: Submodule/FooServer/src/RESTutils.cpp.i
.PHONY : Submodule/FooServer/src/RESTutils.i

# target to preprocess a source file
Submodule/FooServer/src/RESTutils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/Submodule/FooServer/src/RESTutils.cpp.i
.PHONY : Submodule/FooServer/src/RESTutils.cpp.i

Submodule/FooServer/src/RESTutils.s: Submodule/FooServer/src/RESTutils.cpp.s
.PHONY : Submodule/FooServer/src/RESTutils.s

# target to generate assembly for a file
Submodule/FooServer/src/RESTutils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/Submodule/FooServer/src/RESTutils.cpp.s
.PHONY : Submodule/FooServer/src/RESTutils.cpp.s

Submodule/FooServer/src/ServerCmdQueue.o: Submodule/FooServer/src/ServerCmdQueue.cpp.o
.PHONY : Submodule/FooServer/src/ServerCmdQueue.o

# target to build an object file
Submodule/FooServer/src/ServerCmdQueue.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/Submodule/FooServer/src/ServerCmdQueue.cpp.o
.PHONY : Submodule/FooServer/src/ServerCmdQueue.cpp.o

Submodule/FooServer/src/ServerCmdQueue.i: Submodule/FooServer/src/ServerCmdQueue.cpp.i
.PHONY : Submodule/FooServer/src/ServerCmdQueue.i

# target to preprocess a source file
Submodule/FooServer/src/ServerCmdQueue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/Submodule/FooServer/src/ServerCmdQueue.cpp.i
.PHONY : Submodule/FooServer/src/ServerCmdQueue.cpp.i

Submodule/FooServer/src/ServerCmdQueue.s: Submodule/FooServer/src/ServerCmdQueue.cpp.s
.PHONY : Submodule/FooServer/src/ServerCmdQueue.s

# target to generate assembly for a file
Submodule/FooServer/src/ServerCmdQueue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/Submodule/FooServer/src/ServerCmdQueue.cpp.s
.PHONY : Submodule/FooServer/src/ServerCmdQueue.cpp.s

Submodule/FooServer/src/TCPClientInfo.o: Submodule/FooServer/src/TCPClientInfo.cpp.o
.PHONY : Submodule/FooServer/src/TCPClientInfo.o

# target to build an object file
Submodule/FooServer/src/TCPClientInfo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/Submodule/FooServer/src/TCPClientInfo.cpp.o
.PHONY : Submodule/FooServer/src/TCPClientInfo.cpp.o

Submodule/FooServer/src/TCPClientInfo.i: Submodule/FooServer/src/TCPClientInfo.cpp.i
.PHONY : Submodule/FooServer/src/TCPClientInfo.i

# target to preprocess a source file
Submodule/FooServer/src/TCPClientInfo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/Submodule/FooServer/src/TCPClientInfo.cpp.i
.PHONY : Submodule/FooServer/src/TCPClientInfo.cpp.i

Submodule/FooServer/src/TCPClientInfo.s: Submodule/FooServer/src/TCPClientInfo.cpp.s
.PHONY : Submodule/FooServer/src/TCPClientInfo.s

# target to generate assembly for a file
Submodule/FooServer/src/TCPClientInfo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/Submodule/FooServer/src/TCPClientInfo.cpp.s
.PHONY : Submodule/FooServer/src/TCPClientInfo.cpp.s

Submodule/FooServer/src/TCPServer.o: Submodule/FooServer/src/TCPServer.cpp.o
.PHONY : Submodule/FooServer/src/TCPServer.o

# target to build an object file
Submodule/FooServer/src/TCPServer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/Submodule/FooServer/src/TCPServer.cpp.o
.PHONY : Submodule/FooServer/src/TCPServer.cpp.o

Submodule/FooServer/src/TCPServer.i: Submodule/FooServer/src/TCPServer.cpp.i
.PHONY : Submodule/FooServer/src/TCPServer.i

# target to preprocess a source file
Submodule/FooServer/src/TCPServer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/Submodule/FooServer/src/TCPServer.cpp.i
.PHONY : Submodule/FooServer/src/TCPServer.cpp.i

Submodule/FooServer/src/TCPServer.s: Submodule/FooServer/src/TCPServer.cpp.s
.PHONY : Submodule/FooServer/src/TCPServer.s

# target to generate assembly for a file
Submodule/FooServer/src/TCPServer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/Submodule/FooServer/src/TCPServer.cpp.s
.PHONY : Submodule/FooServer/src/TCPServer.cpp.s

Submodule/FooServer/src/Telnet/CmdLineBuffer.o: Submodule/FooServer/src/Telnet/CmdLineBuffer.cpp.o
.PHONY : Submodule/FooServer/src/Telnet/CmdLineBuffer.o

# target to build an object file
Submodule/FooServer/src/Telnet/CmdLineBuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/Submodule/FooServer/src/Telnet/CmdLineBuffer.cpp.o
.PHONY : Submodule/FooServer/src/Telnet/CmdLineBuffer.cpp.o

Submodule/FooServer/src/Telnet/CmdLineBuffer.i: Submodule/FooServer/src/Telnet/CmdLineBuffer.cpp.i
.PHONY : Submodule/FooServer/src/Telnet/CmdLineBuffer.i

# target to preprocess a source file
Submodule/FooServer/src/Telnet/CmdLineBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/Submodule/FooServer/src/Telnet/CmdLineBuffer.cpp.i
.PHONY : Submodule/FooServer/src/Telnet/CmdLineBuffer.cpp.i

Submodule/FooServer/src/Telnet/CmdLineBuffer.s: Submodule/FooServer/src/Telnet/CmdLineBuffer.cpp.s
.PHONY : Submodule/FooServer/src/Telnet/CmdLineBuffer.s

# target to generate assembly for a file
Submodule/FooServer/src/Telnet/CmdLineBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/Submodule/FooServer/src/Telnet/CmdLineBuffer.cpp.s
.PHONY : Submodule/FooServer/src/Telnet/CmdLineBuffer.cpp.s

Submodule/FooServer/src/Telnet/CmdLineHelp.o: Submodule/FooServer/src/Telnet/CmdLineHelp.cpp.o
.PHONY : Submodule/FooServer/src/Telnet/CmdLineHelp.o

# target to build an object file
Submodule/FooServer/src/Telnet/CmdLineHelp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/Submodule/FooServer/src/Telnet/CmdLineHelp.cpp.o
.PHONY : Submodule/FooServer/src/Telnet/CmdLineHelp.cpp.o

Submodule/FooServer/src/Telnet/CmdLineHelp.i: Submodule/FooServer/src/Telnet/CmdLineHelp.cpp.i
.PHONY : Submodule/FooServer/src/Telnet/CmdLineHelp.i

# target to preprocess a source file
Submodule/FooServer/src/Telnet/CmdLineHelp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/Submodule/FooServer/src/Telnet/CmdLineHelp.cpp.i
.PHONY : Submodule/FooServer/src/Telnet/CmdLineHelp.cpp.i

Submodule/FooServer/src/Telnet/CmdLineHelp.s: Submodule/FooServer/src/Telnet/CmdLineHelp.cpp.s
.PHONY : Submodule/FooServer/src/Telnet/CmdLineHelp.s

# target to generate assembly for a file
Submodule/FooServer/src/Telnet/CmdLineHelp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/Submodule/FooServer/src/Telnet/CmdLineHelp.cpp.s
.PHONY : Submodule/FooServer/src/Telnet/CmdLineHelp.cpp.s

Submodule/FooServer/src/Telnet/CmdLineMgr.o: Submodule/FooServer/src/Telnet/CmdLineMgr.cpp.o
.PHONY : Submodule/FooServer/src/Telnet/CmdLineMgr.o

# target to build an object file
Submodule/FooServer/src/Telnet/CmdLineMgr.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/Submodule/FooServer/src/Telnet/CmdLineMgr.cpp.o
.PHONY : Submodule/FooServer/src/Telnet/CmdLineMgr.cpp.o

Submodule/FooServer/src/Telnet/CmdLineMgr.i: Submodule/FooServer/src/Telnet/CmdLineMgr.cpp.i
.PHONY : Submodule/FooServer/src/Telnet/CmdLineMgr.i

# target to preprocess a source file
Submodule/FooServer/src/Telnet/CmdLineMgr.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/Submodule/FooServer/src/Telnet/CmdLineMgr.cpp.i
.PHONY : Submodule/FooServer/src/Telnet/CmdLineMgr.cpp.i

Submodule/FooServer/src/Telnet/CmdLineMgr.s: Submodule/FooServer/src/Telnet/CmdLineMgr.cpp.s
.PHONY : Submodule/FooServer/src/Telnet/CmdLineMgr.s

# target to generate assembly for a file
Submodule/FooServer/src/Telnet/CmdLineMgr.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/Submodule/FooServer/src/Telnet/CmdLineMgr.cpp.s
.PHONY : Submodule/FooServer/src/Telnet/CmdLineMgr.cpp.s

Submodule/FooServer/src/Telnet/CmdLineRegistry.o: Submodule/FooServer/src/Telnet/CmdLineRegistry.cpp.o
.PHONY : Submodule/FooServer/src/Telnet/CmdLineRegistry.o

# target to build an object file
Submodule/FooServer/src/Telnet/CmdLineRegistry.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/Submodule/FooServer/src/Telnet/CmdLineRegistry.cpp.o
.PHONY : Submodule/FooServer/src/Telnet/CmdLineRegistry.cpp.o

Submodule/FooServer/src/Telnet/CmdLineRegistry.i: Submodule/FooServer/src/Telnet/CmdLineRegistry.cpp.i
.PHONY : Submodule/FooServer/src/Telnet/CmdLineRegistry.i

# target to preprocess a source file
Submodule/FooServer/src/Telnet/CmdLineRegistry.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/Submodule/FooServer/src/Telnet/CmdLineRegistry.cpp.i
.PHONY : Submodule/FooServer/src/Telnet/CmdLineRegistry.cpp.i

Submodule/FooServer/src/Telnet/CmdLineRegistry.s: Submodule/FooServer/src/Telnet/CmdLineRegistry.cpp.s
.PHONY : Submodule/FooServer/src/Telnet/CmdLineRegistry.s

# target to generate assembly for a file
Submodule/FooServer/src/Telnet/CmdLineRegistry.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/Submodule/FooServer/src/Telnet/CmdLineRegistry.cpp.s
.PHONY : Submodule/FooServer/src/Telnet/CmdLineRegistry.cpp.s

Submodule/FooServer/src/Telnet/TelnetServerConnection.o: Submodule/FooServer/src/Telnet/TelnetServerConnection.cpp.o
.PHONY : Submodule/FooServer/src/Telnet/TelnetServerConnection.o

# target to build an object file
Submodule/FooServer/src/Telnet/TelnetServerConnection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/Submodule/FooServer/src/Telnet/TelnetServerConnection.cpp.o
.PHONY : Submodule/FooServer/src/Telnet/TelnetServerConnection.cpp.o

Submodule/FooServer/src/Telnet/TelnetServerConnection.i: Submodule/FooServer/src/Telnet/TelnetServerConnection.cpp.i
.PHONY : Submodule/FooServer/src/Telnet/TelnetServerConnection.i

# target to preprocess a source file
Submodule/FooServer/src/Telnet/TelnetServerConnection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/Submodule/FooServer/src/Telnet/TelnetServerConnection.cpp.i
.PHONY : Submodule/FooServer/src/Telnet/TelnetServerConnection.cpp.i

Submodule/FooServer/src/Telnet/TelnetServerConnection.s: Submodule/FooServer/src/Telnet/TelnetServerConnection.cpp.s
.PHONY : Submodule/FooServer/src/Telnet/TelnetServerConnection.s

# target to generate assembly for a file
Submodule/FooServer/src/Telnet/TelnetServerConnection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/Submodule/FooServer/src/Telnet/TelnetServerConnection.cpp.s
.PHONY : Submodule/FooServer/src/Telnet/TelnetServerConnection.cpp.s

Submodule/FooServer/src/Telnet/libtelnet.o: Submodule/FooServer/src/Telnet/libtelnet.c.o
.PHONY : Submodule/FooServer/src/Telnet/libtelnet.o

# target to build an object file
Submodule/FooServer/src/Telnet/libtelnet.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/Submodule/FooServer/src/Telnet/libtelnet.c.o
.PHONY : Submodule/FooServer/src/Telnet/libtelnet.c.o

Submodule/FooServer/src/Telnet/libtelnet.i: Submodule/FooServer/src/Telnet/libtelnet.c.i
.PHONY : Submodule/FooServer/src/Telnet/libtelnet.i

# target to preprocess a source file
Submodule/FooServer/src/Telnet/libtelnet.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/Submodule/FooServer/src/Telnet/libtelnet.c.i
.PHONY : Submodule/FooServer/src/Telnet/libtelnet.c.i

Submodule/FooServer/src/Telnet/libtelnet.s: Submodule/FooServer/src/Telnet/libtelnet.c.s
.PHONY : Submodule/FooServer/src/Telnet/libtelnet.s

# target to generate assembly for a file
Submodule/FooServer/src/Telnet/libtelnet.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/Submodule/FooServer/src/Telnet/libtelnet.c.s
.PHONY : Submodule/FooServer/src/Telnet/libtelnet.c.s

Submodule/FooServer/src/hash-library/sha256.o: Submodule/FooServer/src/hash-library/sha256.cpp.o
.PHONY : Submodule/FooServer/src/hash-library/sha256.o

# target to build an object file
Submodule/FooServer/src/hash-library/sha256.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/Submodule/FooServer/src/hash-library/sha256.cpp.o
.PHONY : Submodule/FooServer/src/hash-library/sha256.cpp.o

Submodule/FooServer/src/hash-library/sha256.i: Submodule/FooServer/src/hash-library/sha256.cpp.i
.PHONY : Submodule/FooServer/src/hash-library/sha256.i

# target to preprocess a source file
Submodule/FooServer/src/hash-library/sha256.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/Submodule/FooServer/src/hash-library/sha256.cpp.i
.PHONY : Submodule/FooServer/src/hash-library/sha256.cpp.i

Submodule/FooServer/src/hash-library/sha256.s: Submodule/FooServer/src/hash-library/sha256.cpp.s
.PHONY : Submodule/FooServer/src/hash-library/sha256.s

# target to generate assembly for a file
Submodule/FooServer/src/hash-library/sha256.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/Submodule/FooServer/src/hash-library/sha256.cpp.s
.PHONY : Submodule/FooServer/src/hash-library/sha256.cpp.s

src/ServerCmdValidators.o: src/ServerCmdValidators.cpp.o
.PHONY : src/ServerCmdValidators.o

# target to build an object file
src/ServerCmdValidators.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/src/ServerCmdValidators.cpp.o
.PHONY : src/ServerCmdValidators.cpp.o

src/ServerCmdValidators.i: src/ServerCmdValidators.cpp.i
.PHONY : src/ServerCmdValidators.i

# target to preprocess a source file
src/ServerCmdValidators.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/src/ServerCmdValidators.cpp.i
.PHONY : src/ServerCmdValidators.cpp.i

src/ServerCmdValidators.s: src/ServerCmdValidators.cpp.s
.PHONY : src/ServerCmdValidators.s

# target to generate assembly for a file
src/ServerCmdValidators.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/src/ServerCmdValidators.cpp.s
.PHONY : src/ServerCmdValidators.cpp.s

src/ServerCommands.o: src/ServerCommands.cpp.o
.PHONY : src/ServerCommands.o

# target to build an object file
src/ServerCommands.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/src/ServerCommands.cpp.o
.PHONY : src/ServerCommands.cpp.o

src/ServerCommands.i: src/ServerCommands.cpp.i
.PHONY : src/ServerCommands.i

# target to preprocess a source file
src/ServerCommands.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/src/ServerCommands.cpp.i
.PHONY : src/ServerCommands.cpp.i

src/ServerCommands.s: src/ServerCommands.cpp.s
.PHONY : src/ServerCommands.s

# target to generate assembly for a file
src/ServerCommands.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/src/ServerCommands.cpp.s
.PHONY : src/ServerCommands.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InsteonMgr.dir/build.make CMakeFiles/InsteonMgr.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... copy_assets"
	@echo "... InsteonMgr"
	@echo "... InsteonMgr/Action.o"
	@echo "... InsteonMgr/Action.i"
	@echo "... InsteonMgr/Action.s"
	@echo "... InsteonMgr/DeviceID.o"
	@echo "... InsteonMgr/DeviceID.i"
	@echo "... InsteonMgr/DeviceID.s"
	@echo "... InsteonMgr/DeviceInfo.o"
	@echo "... InsteonMgr/DeviceInfo.i"
	@echo "... InsteonMgr/DeviceInfo.s"
	@echo "... InsteonMgr/Event.o"
	@echo "... InsteonMgr/Event.i"
	@echo "... InsteonMgr/Event.s"
	@echo "... InsteonMgr/InsteonALDB.o"
	@echo "... InsteonMgr/InsteonALDB.i"
	@echo "... InsteonMgr/InsteonALDB.s"
	@echo "... InsteonMgr/InsteonAPISecretMgr.o"
	@echo "... InsteonMgr/InsteonAPISecretMgr.i"
	@echo "... InsteonMgr/InsteonAPISecretMgr.s"
	@echo "... InsteonMgr/InsteonCmdQueue.o"
	@echo "... InsteonMgr/InsteonCmdQueue.i"
	@echo "... InsteonMgr/InsteonCmdQueue.s"
	@echo "... InsteonMgr/InsteonDB.o"
	@echo "... InsteonMgr/InsteonDB.i"
	@echo "... InsteonMgr/InsteonDB.s"
	@echo "... InsteonMgr/InsteonDevice.o"
	@echo "... InsteonMgr/InsteonDevice.i"
	@echo "... InsteonMgr/InsteonDevice.s"
	@echo "... InsteonMgr/InsteonDeviceEventMgr.o"
	@echo "... InsteonMgr/InsteonDeviceEventMgr.i"
	@echo "... InsteonMgr/InsteonDeviceEventMgr.s"
	@echo "... InsteonMgr/InsteonLinking.o"
	@echo "... InsteonMgr/InsteonLinking.i"
	@echo "... InsteonMgr/InsteonLinking.s"
	@echo "... InsteonMgr/InsteonMgr.o"
	@echo "... InsteonMgr/InsteonMgr.i"
	@echo "... InsteonMgr/InsteonMgr.s"
	@echo "... InsteonMgr/InsteonPLM.o"
	@echo "... InsteonMgr/InsteonPLM.i"
	@echo "... InsteonMgr/InsteonPLM.s"
	@echo "... InsteonMgr/InsteonParser.o"
	@echo "... InsteonMgr/InsteonParser.i"
	@echo "... InsteonMgr/InsteonParser.s"
	@echo "... InsteonMgr/InsteonValidator.o"
	@echo "... InsteonMgr/InsteonValidator.i"
	@echo "... InsteonMgr/InsteonValidator.s"
	@echo "... InsteonMgr/LogMgr.o"
	@echo "... InsteonMgr/LogMgr.i"
	@echo "... InsteonMgr/LogMgr.s"
	@echo "... InsteonMgr/NotificationCenter.o"
	@echo "... InsteonMgr/NotificationCenter.i"
	@echo "... InsteonMgr/NotificationCenter.s"
	@echo "... InsteonMgr/PLMStream.o"
	@echo "... InsteonMgr/PLMStream.i"
	@echo "... InsteonMgr/PLMStream.s"
	@echo "... InsteonMgr/ScheduleMgr.o"
	@echo "... InsteonMgr/ScheduleMgr.i"
	@echo "... InsteonMgr/ScheduleMgr.s"
	@echo "... InsteonMgr/TimeStamp.o"
	@echo "... InsteonMgr/TimeStamp.i"
	@echo "... InsteonMgr/TimeStamp.s"
	@echo "... InsteonMgr/sleep.o"
	@echo "... InsteonMgr/sleep.i"
	@echo "... InsteonMgr/sleep.s"
	@echo "... InsteonMgr/sunset.o"
	@echo "... InsteonMgr/sunset.i"
	@echo "... InsteonMgr/sunset.s"
	@echo "... InsteonMgr/xxhash.o"
	@echo "... InsteonMgr/xxhash.i"
	@echo "... InsteonMgr/xxhash.s"
	@echo "... Submodule/FooServer/src/REST/RESTServerConnection.o"
	@echo "... Submodule/FooServer/src/REST/RESTServerConnection.i"
	@echo "... Submodule/FooServer/src/REST/RESTServerConnection.s"
	@echo "... Submodule/FooServer/src/REST/REST_URL.o"
	@echo "... Submodule/FooServer/src/REST/REST_URL.i"
	@echo "... Submodule/FooServer/src/REST/REST_URL.s"
	@echo "... Submodule/FooServer/src/REST/http_parser.o"
	@echo "... Submodule/FooServer/src/REST/http_parser.i"
	@echo "... Submodule/FooServer/src/REST/http_parser.s"
	@echo "... Submodule/FooServer/src/REST/yuarel.o"
	@echo "... Submodule/FooServer/src/REST/yuarel.i"
	@echo "... Submodule/FooServer/src/REST/yuarel.s"
	@echo "... Submodule/FooServer/src/RESTutils.o"
	@echo "... Submodule/FooServer/src/RESTutils.i"
	@echo "... Submodule/FooServer/src/RESTutils.s"
	@echo "... Submodule/FooServer/src/ServerCmdQueue.o"
	@echo "... Submodule/FooServer/src/ServerCmdQueue.i"
	@echo "... Submodule/FooServer/src/ServerCmdQueue.s"
	@echo "... Submodule/FooServer/src/TCPClientInfo.o"
	@echo "... Submodule/FooServer/src/TCPClientInfo.i"
	@echo "... Submodule/FooServer/src/TCPClientInfo.s"
	@echo "... Submodule/FooServer/src/TCPServer.o"
	@echo "... Submodule/FooServer/src/TCPServer.i"
	@echo "... Submodule/FooServer/src/TCPServer.s"
	@echo "... Submodule/FooServer/src/Telnet/CmdLineBuffer.o"
	@echo "... Submodule/FooServer/src/Telnet/CmdLineBuffer.i"
	@echo "... Submodule/FooServer/src/Telnet/CmdLineBuffer.s"
	@echo "... Submodule/FooServer/src/Telnet/CmdLineHelp.o"
	@echo "... Submodule/FooServer/src/Telnet/CmdLineHelp.i"
	@echo "... Submodule/FooServer/src/Telnet/CmdLineHelp.s"
	@echo "... Submodule/FooServer/src/Telnet/CmdLineMgr.o"
	@echo "... Submodule/FooServer/src/Telnet/CmdLineMgr.i"
	@echo "... Submodule/FooServer/src/Telnet/CmdLineMgr.s"
	@echo "... Submodule/FooServer/src/Telnet/CmdLineRegistry.o"
	@echo "... Submodule/FooServer/src/Telnet/CmdLineRegistry.i"
	@echo "... Submodule/FooServer/src/Telnet/CmdLineRegistry.s"
	@echo "... Submodule/FooServer/src/Telnet/TelnetServerConnection.o"
	@echo "... Submodule/FooServer/src/Telnet/TelnetServerConnection.i"
	@echo "... Submodule/FooServer/src/Telnet/TelnetServerConnection.s"
	@echo "... Submodule/FooServer/src/Telnet/libtelnet.o"
	@echo "... Submodule/FooServer/src/Telnet/libtelnet.i"
	@echo "... Submodule/FooServer/src/Telnet/libtelnet.s"
	@echo "... Submodule/FooServer/src/hash-library/sha256.o"
	@echo "... Submodule/FooServer/src/hash-library/sha256.i"
	@echo "... Submodule/FooServer/src/hash-library/sha256.s"
	@echo "... src/ServerCmdValidators.o"
	@echo "... src/ServerCmdValidators.i"
	@echo "... src/ServerCmdValidators.s"
	@echo "... src/ServerCommands.o"
	@echo "... src/ServerCommands.i"
	@echo "... src/ServerCommands.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

